# Generated by Django 6.0.3 on 2026-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.URLField(default='', max_length=500),
        ),
    ]
